<?php

return [
    'fixed' => [
        [
            'key' => 'yeni-yil',
            'name' => 'Yeni Yıl',
            'month' => 1,
            'day' => 1,
            'category' => 'genel',
            'default_prompt' => 'Yeni yıl için B2B seyahat dünyasına uygun kutlama görseli ve mesajı oluştur.',
            'priority' => 120,
        ],
        [
            'key' => 'ulusal-egemenlik',
            'name' => '23 Nisan Ulusal Egemenlik ve Çocuk Bayramı',
            'month' => 4,
            'day' => 23,
            'category' => 'milli',
            'default_prompt' => '23 Nisan için kurumsal ve saygılı bir kutlama görseli ve mesajı oluştur.',
            'priority' => 80,
        ],
        [
            'key' => 'genclik-spor',
            'name' => "19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı",
            'month' => 5,
            'day' => 19,
            'category' => 'milli',
            'default_prompt' => '19 Mayıs için kurumsal kutlama görseli ve mesajı oluştur.',
            'priority' => 80,
        ],
        [
            'key' => 'zafer-bayrami',
            'name' => '30 Ağustos Zafer Bayramı',
            'month' => 8,
            'day' => 30,
            'category' => 'milli',
            'default_prompt' => '30 Ağustos için kurumsal kutlama görseli ve mesajı oluştur.',
            'priority' => 80,
        ],
        [
            'key' => 'cumhuriyet-bayrami',
            'name' => '29 Ekim Cumhuriyet Bayramı',
            'month' => 10,
            'day' => 29,
            'category' => 'milli',
            'default_prompt' => '29 Ekim için kurumsal kutlama görseli ve mesajı oluştur.',
            'priority' => 70,
        ],
        [
            'key' => 'ogretmenler-gunu',
            'name' => 'Öğretmenler Günü',
            'month' => 11,
            'day' => 24,
            'category' => 'ozel',
            'default_prompt' => 'Öğretmenler Günü için sade ve samimi kutlama görseli ve mesajı oluştur.',
            'priority' => 120,
        ],
        [
            'key' => 'yesilay-haftasi',
            'name' => 'Yeşilay Haftası (1-7 Mart)',
            'month' => 3,
            'day' => 1,
            'category' => 'farkindalik',
            'default_prompt' => 'Yeşilay Haftası için kurumsal, pozitif ve farkındalık odaklı bir kutlama görseli oluştur.',
            'priority' => 180,
        ],
        [
            'key' => 'deprem-haftasi',
            'name' => 'Deprem Haftası (1-7 Mart)',
            'month' => 3,
            'day' => 1,
            'category' => 'farkindalik',
            'default_prompt' => 'Deprem Haftası için bilinçlendirici, sade ve kurumsal bir görsel oluştur.',
            'priority' => 185,
        ],
        [
            'key' => 'girisimcilik-haftasi',
            'name' => 'Girişimcilik Haftası (1-7 Mart)',
            'month' => 3,
            'day' => 1,
            'category' => 'farkindalik',
            'default_prompt' => 'Girişimcilik Haftası için vizyoner, kurumsal ve ilham verici bir kutlama görseli oluştur.',
            'priority' => 190,
        ],
        [
            'key' => 'dunya-kadinlar-gunu',
            'name' => 'Dünya Kadınlar Günü',
            'month' => 3,
            'day' => 8,
            'category' => 'ozel',
            'default_prompt' => 'Dünya Kadınlar Günü için zarif, saygılı ve kurumsal bir kutlama görseli oluştur.',
            'priority' => 95,
        ],
        [
            'key' => 'bilim-teknoloji-haftasi',
            'name' => 'Bilim ve Teknoloji Haftası (8-14 Mart)',
            'month' => 3,
            'day' => 8,
            'category' => 'farkindalik',
            'default_prompt' => 'Bilim ve Teknoloji Haftası için modern, yenilikçi ve kurumsal bir kutlama görseli oluştur.',
            'priority' => 160,
        ],
        [
            'key' => 'istiklal-marsi-kabulu',
            'name' => "İstiklal Marşı'nın Kabulü ve Mehmet Akif Ersoy'u Anma Günü",
            'month' => 3,
            'day' => 12,
            'category' => 'milli',
            'default_prompt' => "İstiklal Marşı'nın Kabulü için saygılı, sade ve kurumsal bir anma görseli oluştur.",
            'priority' => 65,
        ],
        [
            'key' => 'tip-bayrami',
            'name' => 'Tıp Bayramı',
            'month' => 3,
            'day' => 14,
            'category' => 'ozel',
            'default_prompt' => 'Tıp Bayramı için teşekkür odaklı, sade ve kurumsal bir kutlama görseli oluştur.',
            'priority' => 130,
        ],
        [
            'key' => 'dunya-pi-gunu',
            'name' => 'Dünya Pi Günü',
            'month' => 3,
            'day' => 14,
            'category' => 'farkindalik',
            'default_prompt' => 'Dünya Pi Günü için yaratıcı, modern ve kurumsal bir kutlama görseli oluştur.',
            'priority' => 210,
        ],
        [
            'key' => 'dunya-tuketiciler-gunu',
            'name' => 'Dünya Tüketiciler Günü',
            'month' => 3,
            'day' => 15,
            'category' => 'farkindalik',
            'default_prompt' => 'Dünya Tüketiciler Günü için bilgilendirici, sade ve kurumsal bir görsel oluştur.',
            'priority' => 200,
        ],
        [
            'key' => 'canakkale-zaferi',
            'name' => 'Çanakkale Zaferi ve Şehitleri Anma Günü',
            'month' => 3,
            'day' => 18,
            'category' => 'milli',
            'default_prompt' => 'Çanakkale Zaferi için saygılı, anma odaklı ve kurumsal bir görsel oluştur.',
            'priority' => 62,
        ],
        [
            'key' => 'yaslilara-saygi-haftasi',
            'name' => 'Yaşlılara Saygı Haftası (18-24 Mart)',
            'month' => 3,
            'day' => 18,
            'category' => 'farkindalik',
            'default_prompt' => 'Yaşlılara Saygı Haftası için sıcak, saygılı ve kurumsal bir kutlama görseli oluştur.',
            'priority' => 170,
        ],
        [
            'key' => 'dunya-mutluluk-gunu',
            'name' => 'Dünya Mutluluk Günü',
            'month' => 3,
            'day' => 20,
            'category' => 'ozel',
            'default_prompt' => 'Dünya Mutluluk Günü için pozitif, enerjik ve kurumsal bir kutlama görseli oluştur.',
            'priority' => 175,
        ],
        [
            'key' => 'nevruz-bayrami',
            'name' => 'Nevruz Bayramı',
            'month' => 3,
            'day' => 21,
            'category' => 'kulturel',
            'default_prompt' => 'Nevruz Bayramı için bahar temalı, renkli ama kurumsal bir kutlama görseli oluştur.',
            'priority' => 140,
        ],
        [
            'key' => 'down-sendromu-farkindalik',
            'name' => 'Dünya Down Sendromu Farkındalık Günü',
            'month' => 3,
            'day' => 21,
            'category' => 'farkindalik',
            'default_prompt' => 'Down Sendromu Farkındalık Günü için kapsayıcı ve pozitif bir görsel oluştur.',
            'priority' => 165,
        ],
        [
            'key' => 'orman-haftasi',
            'name' => 'Orman Haftası (21-26 Mart)',
            'month' => 3,
            'day' => 21,
            'category' => 'farkindalik',
            'default_prompt' => 'Orman Haftası için doğa odaklı, temiz ve kurumsal bir görsel oluştur.',
            'priority' => 195,
        ],
        [
            'key' => 'dunya-su-gunu',
            'name' => 'Dünya Su Günü',
            'month' => 3,
            'day' => 22,
            'category' => 'farkindalik',
            'default_prompt' => 'Dünya Su Günü için temiz, mavi tonlarda ve farkındalık odaklı bir görsel oluştur.',
            'priority' => 198,
        ],
        [
            'key' => 'dunya-meteoroloji-gunu',
            'name' => 'Dünya Meteoroloji Günü',
            'month' => 3,
            'day' => 23,
            'category' => 'farkindalik',
            'default_prompt' => 'Dünya Meteoroloji Günü için modern, bilgilendirici ve kurumsal bir görsel oluştur.',
            'priority' => 205,
        ],
        [
            'key' => 'dunya-tiyatro-gunu',
            'name' => 'Dünya Tiyatro Günü',
            'month' => 3,
            'day' => 27,
            'category' => 'kulturel',
            'default_prompt' => 'Dünya Tiyatro Günü için sanatsal, sade ve kurumsal bir kutlama görseli oluştur.',
            'priority' => 220,
        ],
    ],

    'floating' => [
        [
            'key' => 'anneler-gunu',
            'name' => 'Anneler Günü',
            'rule' => 'second_sunday_may',
            'category' => 'ozel',
            'default_prompt' => 'Anneler Günü için zarif ve samimi bir kutlama görseli ve mesajı oluştur.',
            'priority' => 100,
        ],
        [
            'key' => 'babalar-gunu',
            'name' => 'Babalar Günü',
            'rule' => 'third_sunday_june',
            'category' => 'ozel',
            'default_prompt' => 'Babalar Günü için sade, kurumsal ve samimi bir kutlama görseli oluştur.',
            'priority' => 110,
        ],
        [
            'key' => 'kutuphane-haftasi',
            'name' => 'Kütüphane Haftası (Mart Son Pazartesi)',
            'rule' => 'last_monday_march',
            'category' => 'farkindalik',
            'default_prompt' => 'Kütüphane Haftası için eğitim odaklı, sade ve kurumsal bir kutlama görseli oluştur.',
            'priority' => 215,
        ],
    ],

    'yearly' => [
        2026 => [
            [
                'key' => 'kadir-gecesi',
                'name' => 'Kadir Gecesi',
                'date' => '2026-03-17',
                'category' => 'dini',
                'default_prompt' => 'Kadir Gecesi için saygılı, sade ve kurumsal bir kutlama görseli oluştur.',
                'priority' => 60,
            ],
            [
                'key' => 'ramazan-bayrami-1',
                'name' => 'Ramazan Bayramı',
                'date' => '2026-03-20',
                'category' => 'dini',
                'default_prompt' => 'Ramazan Bayramı için kurumsal bir kutlama görseli ve mesajı oluştur.',
                'priority' => 55,
            ],
        ],
    ],
];
