<?php

return [
    'fixed' => [
        [
            'key' => 'yeni-yil',
            'name' => 'Yeni Yil',
            'month' => 1,
            'day' => 1,
            'category' => 'genel',
            'default_prompt' => 'Yeni yil icin B2B seyahat dunyasina uygun kutlama gorseli ve mesaji olustur.',
            'priority' => 120,
        ],
        [
            'key' => 'ulusal-egemenlik',
            'name' => '23 Nisan Ulusal Egemenlik ve Cocuk Bayrami',
            'month' => 4,
            'day' => 23,
            'category' => 'milli',
            'default_prompt' => '23 Nisan icin kurumsal ve saygili bir kutlama gorseli ve mesaji olustur.',
            'priority' => 80,
        ],
        [
            'key' => 'genclik-spor',
            'name' => '19 Mayis Ataturk\'u Anma, Genclik ve Spor Bayrami',
            'month' => 5,
            'day' => 19,
            'category' => 'milli',
            'default_prompt' => '19 Mayis icin kurumsal kutlama gorseli ve mesaji olustur.',
            'priority' => 80,
        ],
        [
            'key' => 'zafer-bayrami',
            'name' => '30 Agustos Zafer Bayrami',
            'month' => 8,
            'day' => 30,
            'category' => 'milli',
            'default_prompt' => '30 Agustos icin kurumsal kutlama gorseli ve mesaji olustur.',
            'priority' => 80,
        ],
        [
            'key' => 'cumhuriyet-bayrami',
            'name' => '29 Ekim Cumhuriyet Bayrami',
            'month' => 10,
            'day' => 29,
            'category' => 'milli',
            'default_prompt' => '29 Ekim icin kurumsal kutlama gorseli ve mesaji olustur.',
            'priority' => 70,
        ],
        [
            'key' => 'ogretmenler-gunu',
            'name' => 'Ogretmenler Gunu',
            'month' => 11,
            'day' => 24,
            'category' => 'ozel',
            'default_prompt' => 'Ogretmenler Gunu icin sade ve samimi kutlama gorseli ve mesaji olustur.',
            'priority' => 120,
        ],
        [
            'key' => 'yesilay-haftasi',
            'name' => 'Yesilay Haftasi (1-7 Mart)',
            'month' => 3,
            'day' => 1,
            'category' => 'farkindalik',
            'default_prompt' => 'Yesilay Haftasi icin kurumsal, pozitif ve farkindalik odakli bir kutlama gorseli olustur.',
            'priority' => 180,
        ],
        [
            'key' => 'deprem-haftasi',
            'name' => 'Deprem Haftasi (1-7 Mart)',
            'month' => 3,
            'day' => 1,
            'category' => 'farkindalik',
            'default_prompt' => 'Deprem Haftasi icin bilinclendirici, sade ve kurumsal bir gorsel olustur.',
            'priority' => 185,
        ],
        [
            'key' => 'girisimcilik-haftasi',
            'name' => 'Girisimcilik Haftasi (1-7 Mart)',
            'month' => 3,
            'day' => 1,
            'category' => 'farkindalik',
            'default_prompt' => 'Girisimcilik Haftasi icin vizyoner, kurumsal ve ilham verici bir kutlama gorseli olustur.',
            'priority' => 190,
        ],
        [
            'key' => 'dunya-kadinlar-gunu',
            'name' => 'Dunya Kadinlar Gunu',
            'month' => 3,
            'day' => 8,
            'category' => 'ozel',
            'default_prompt' => 'Dunya Kadinlar Gunu icin zarif, saygili ve kurumsal bir kutlama gorseli olustur.',
            'priority' => 95,
        ],
        [
            'key' => 'bilim-teknoloji-haftasi',
            'name' => 'Bilim ve Teknoloji Haftasi (8-14 Mart)',
            'month' => 3,
            'day' => 8,
            'category' => 'farkindalik',
            'default_prompt' => 'Bilim ve Teknoloji Haftasi icin modern, yenilikci ve kurumsal bir kutlama gorseli olustur.',
            'priority' => 160,
        ],
        [
            'key' => 'istiklal-marsi-kabulu',
            'name' => 'Istiklal Marsi\'nin Kabulu ve Mehmet Akif Ersoy\'u Anma Gunu',
            'month' => 3,
            'day' => 12,
            'category' => 'milli',
            'default_prompt' => 'Istiklal Marsi\'nin Kabulu icin saygili, sade ve kurumsal bir anma gorseli olustur.',
            'priority' => 65,
        ],
        [
            'key' => 'tip-bayrami',
            'name' => 'Tip Bayrami',
            'month' => 3,
            'day' => 14,
            'category' => 'ozel',
            'default_prompt' => 'Tip Bayrami icin tesekkur odakli, sade ve kurumsal bir kutlama gorseli olustur.',
            'priority' => 130,
        ],
        [
            'key' => 'dunya-pi-gunu',
            'name' => 'Dunya Pi Gunu',
            'month' => 3,
            'day' => 14,
            'category' => 'farkindalik',
            'default_prompt' => 'Dunya Pi Gunu icin yaratci, modern ve kurumsal bir kutlama gorseli olustur.',
            'priority' => 210,
        ],
        [
            'key' => 'dunya-tuketiciler-gunu',
            'name' => 'Dunya Tuketiciler Gunu',
            'month' => 3,
            'day' => 15,
            'category' => 'farkindalik',
            'default_prompt' => 'Dunya Tuketiciler Gunu icin bilgilendirici, sade ve kurumsal bir gorsel olustur.',
            'priority' => 200,
        ],
        [
            'key' => 'canakkale-zaferi',
            'name' => 'Canakkale Zaferi ve Sehitleri Anma Gunu',
            'month' => 3,
            'day' => 18,
            'category' => 'milli',
            'default_prompt' => 'Canakkale Zaferi icin saygili, anma odakli ve kurumsal bir gorsel olustur.',
            'priority' => 62,
        ],
        [
            'key' => 'yaslilara-saygi-haftasi',
            'name' => 'Yaslilara Saygi Haftasi (18-24 Mart)',
            'month' => 3,
            'day' => 18,
            'category' => 'farkindalik',
            'default_prompt' => 'Yaslilara Saygi Haftasi icin sicak, saygili ve kurumsal bir kutlama gorseli olustur.',
            'priority' => 170,
        ],
        [
            'key' => 'dunya-mutluluk-gunu',
            'name' => 'Dunya Mutluluk Gunu',
            'month' => 3,
            'day' => 20,
            'category' => 'ozel',
            'default_prompt' => 'Dunya Mutluluk Gunu icin pozitif, enerjik ve kurumsal bir kutlama gorseli olustur.',
            'priority' => 175,
        ],
        [
            'key' => 'nevruz-bayrami',
            'name' => 'Nevruz Bayrami',
            'month' => 3,
            'day' => 21,
            'category' => 'kulturel',
            'default_prompt' => 'Nevruz Bayrami icin bahar temali, renkli ama kurumsal bir kutlama gorseli olustur.',
            'priority' => 140,
        ],
        [
            'key' => 'down-sendromu-farkindalik',
            'name' => 'Dunya Down Sendromu Farkindalik Gunu',
            'month' => 3,
            'day' => 21,
            'category' => 'farkindalik',
            'default_prompt' => 'Down Sendromu Farkindalik Gunu icin kapsayici ve pozitif bir gorsel olustur.',
            'priority' => 165,
        ],
        [
            'key' => 'orman-haftasi',
            'name' => 'Orman Haftasi (21-26 Mart)',
            'month' => 3,
            'day' => 21,
            'category' => 'farkindalik',
            'default_prompt' => 'Orman Haftasi icin doga odakli, temiz ve kurumsal bir gorsel olustur.',
            'priority' => 195,
        ],
        [
            'key' => 'dunya-su-gunu',
            'name' => 'Dunya Su Gunu',
            'month' => 3,
            'day' => 22,
            'category' => 'farkindalik',
            'default_prompt' => 'Dunya Su Gunu icin temiz, mavi tonlarda ve farkindalik odakli bir gorsel olustur.',
            'priority' => 198,
        ],
        [
            'key' => 'dunya-meteoroloji-gunu',
            'name' => 'Dunya Meteoroloji Gunu',
            'month' => 3,
            'day' => 23,
            'category' => 'farkindalik',
            'default_prompt' => 'Dunya Meteoroloji Gunu icin modern, bilgilendirici ve kurumsal bir gorsel olustur.',
            'priority' => 205,
        ],
        [
            'key' => 'dunya-tiyatro-gunu',
            'name' => 'Dunya Tiyatro Gunu',
            'month' => 3,
            'day' => 27,
            'category' => 'kulturel',
            'default_prompt' => 'Dunya Tiyatro Gunu icin sanatsal, sade ve kurumsal bir kutlama gorseli olustur.',
            'priority' => 220,
        ],
    ],

    'floating' => [
        [
            'key' => 'anneler-gunu',
            'name' => 'Anneler Gunu',
            'rule' => 'second_sunday_may',
            'category' => 'ozel',
            'default_prompt' => 'Anneler Gunu icin zarif ve samimi bir kutlama gorseli ve mesaji olustur.',
            'priority' => 100,
        ],
        [
            'key' => 'babalar-gunu',
            'name' => 'Babalar Gunu',
            'rule' => 'third_sunday_june',
            'category' => 'ozel',
            'default_prompt' => 'Babalar Gunu icin sade, kurumsal ve samimi bir kutlama gorseli olustur.',
            'priority' => 110,
        ],
        [
            'key' => 'kutuphane-haftasi',
            'name' => 'Kutuphane Haftasi (Mart Son Pazartesi)',
            'rule' => 'last_monday_march',
            'category' => 'farkindalik',
            'default_prompt' => 'Kutuphane Haftasi icin egitim odakli, sade ve kurumsal bir kutlama gorseli olustur.',
            'priority' => 215,
        ],
    ],

    'yearly' => [
        2026 => [
            [
                'key' => 'kadir-gecesi',
                'name' => 'Kadir Gecesi',
                'date' => '2026-03-17',
                'category' => 'dini',
                'default_prompt' => 'Kadir Gecesi icin saygili, sade ve kurumsal bir kutlama gorseli olustur.',
                'priority' => 60,
            ],
            [
                'key' => 'ramazan-bayrami-1',
                'name' => 'Ramazan Bayrami',
                'date' => '2026-03-20',
                'category' => 'dini',
                'default_prompt' => 'Ramazan Bayrami icin kurumsal bir kutlama gorseli ve mesaji olustur.',
                'priority' => 55,
            ],
        ],
    ],
];
